const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://akshaykumarbolusani.vercel.app";

export const site = {
  name: "Akshay Kumar Bolusani",
  shortName: "Akshay",
  brand: "Akshay Labs",
  role: "Software Engineer · Full Stack Developer · AI/ML Engineer",
  tagline: "Building Ideas Into Reality",
  location: "Hyderabad, India",
  locationDetailed: {
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    countryCode: "IN",
  },
  email: "akshaykumarbolusani@gmail.com",
  url: SITE_URL,
  image: "/akshay.webp",
  ogImage: "/og-image.png",
  description:
    "Akshay Kumar Bolusani is a Software Engineer, Full Stack Developer, and AI/ML Engineer based in Hyderabad, India. Former Web Development Intern at Digital Connect (September 2022 – January 2026). Portfolio spans AI, full-stack, and research projects.",
  longDescription:
    "Akshay Kumar Bolusani is a passionate Software Engineer specializing in Full Stack Development and Artificial Intelligence. With expertise in Next.js, React, Python, and machine learning frameworks, Akshay builds innovative solutions ranging from AI-powered healthcare applications to enterprise-grade web platforms. A B.Tech graduate in Computer Science Engineering with experience as a Web Development Intern at Digital Connect, Akshay has delivered 100+ websites and 50+ technical projects across diverse domains.",
  socials: {
    linkedin: "https://www.linkedin.com/in/akshaykumarbolusani/",
    github: "https://github.com/AkshayKumarBolusani",
    instagram: "https://www.instagram.com/askforakshaykumar/",
  },
  keywords: [
    "Akshay Kumar Bolusani",
    "Bolusani Akshay Kumar",
    "Software Engineer Hyderabad",
    "Full Stack Developer Hyderabad",
    "AI Developer Hyderabad",
    "Machine Learning Engineer Hyderabad",
    "React Developer Hyderabad",
    "Python Developer Hyderabad",
    "AI Engineer",
    "Next.js Developer",
    "Portfolio",
    "Web Developer India",
    "Computer Vision Engineer",
    "LLM Developer",
    "RAG Systems",
    "Deep Learning Engineer",
    "TypeScript Developer",
    "ProjectKaro",
  ],
  skills: {
    languages: ["Python", "TypeScript", "JavaScript", "SQL", "HTML", "CSS"],
    frontend: ["React", "Next.js", "Tailwind CSS", "Framer Motion", "Three.js"],
    backend: ["Node.js", "FastAPI", "Express", "Django"],
    ai: ["PyTorch", "TensorFlow", "LangChain", "OpenAI", "Hugging Face", "Computer Vision", "NLP"],
    databases: ["PostgreSQL", "MongoDB", "Redis", "Pinecone", "ChromaDB"],
    cloud: ["AWS", "Vercel", "Docker", "Kubernetes"],
    tools: ["Git", "GitHub", "VS Code", "Figma"],
  },
  expertise: [
    "Full Stack Web Development",
    "Artificial Intelligence & Machine Learning",
    "Computer Vision & Image Processing",
    "Natural Language Processing",
    "Large Language Models (LLMs)",
    "RAG (Retrieval-Augmented Generation) Systems",
    "Deep Learning & Neural Networks",
    "API Development & Integration",
    "Database Design & Optimization",
    "Cloud Architecture & DevOps",
  ],
  projectKaro: {
    name: "ProjectKaro",
    url: "https://projectkaro.com",
    description: "Professional services platform for technical solutions including website development, AI solutions, full-stack applications, and technical consulting.",
  },
  education: {
    degree: "Bachelor of Technology in Computer Science Engineering",
    status: "Completed",
    graduationYear: "2026",
  },
  work: {
    company: "Digital Connect",
    role: "Web Development Intern",
    period: "September 2022 – January 2026",
  },
  availability: [
    "Collaborations",
    "Freelancing",
    "Software Engineering Opportunities",
    "AI/ML Opportunities",
  ],
  languages: ["English", "Hindi", "Telugu"],
  birthYear: 2004,
} as const;

export const nav = [
  { id: "home", label: "HOME", href: "#home" },
  { id: "about", label: "ABOUT", href: "#about" },
  { id: "projects", label: "VAULT", href: "#projects" },
  { id: "blog", label: "BLOG", href: "/blog" },
  { id: "projectkaro", label: "PROJECTKARO", href: "#projectkaro" },
  { id: "recruiters", label: "RECRUITERS", href: "#recruiters" },
  { id: "contact", label: "CONTACT", href: "#contact" },
] as const;
